# coding: utf-8

"""
    ParallelStack RSearch API

    REST API Specification for ParallelStack RSearch API

    OpenAPI spec version: 1.0.0
    Contact: team@parallelstack.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import rsearch_client
from rsearch_client.rest import ApiException
from rsearch_client.models.get_doctype_success import GetDoctypeSuccess


class TestGetDoctypeSuccess(unittest.TestCase):
    """ GetDoctypeSuccess unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetDoctypeSuccess(self):
        """
        Test GetDoctypeSuccess
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = rsearch_client.models.get_doctype_success.GetDoctypeSuccess()
        pass


if __name__ == '__main__':
    unittest.main()
