# coding: utf-8

"""
    ParallelStack RSearch API

    REST API Specification for ParallelStack RSearch API

    OpenAPI spec version: 1.0.0
    Contact: team@parallelstack.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import rsearch_client
from rsearch_client.rest import ApiException
from rsearch_client.models.inline_response_200_4 import InlineResponse2004


class TestInlineResponse2004(unittest.TestCase):
    """ InlineResponse2004 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2004(self):
        """
        Test InlineResponse2004
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = rsearch_client.models.inline_response_200_4.InlineResponse2004()
        pass


if __name__ == '__main__':
    unittest.main()
