# coding: utf-8

"""
    ParallelStack RSearch API

    REST API Specification for ParallelStack RSearch API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: team@parallelstack.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import rsearch_client
from .get_doc_type_failure import GetDocTypeFailure  # noqa: E501
from rsearch_client.rest import ApiException


class TestGetDocTypeFailure(unittest.TestCase):
    """GetDocTypeFailure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetDocTypeFailure(self):
        """Test GetDocTypeFailure"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rsearch_client.models.get_doc_type_failure.GetDocTypeFailure()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
