# coding: utf-8

"""
    ParallelStack RSearch API

    REST API Specification for ParallelStack RSearch API.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: team@parallelstack.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import rsearch_client
from .create_document_success import CreateDocumentSuccess  # noqa: E501
from rsearch_client.rest import ApiException


class TestCreateDocumentSuccess(unittest.TestCase):
    """CreateDocumentSuccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateDocumentSuccess(self):
        """Test CreateDocumentSuccess"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rsearch_client.models.create_document_success.CreateDocumentSuccess()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
