# coding: utf-8

"""
    ParallelStack RSearch API

    REST API Specification for ParallelStack RSearch API  # noqa: E501

    OpenAPI spec version: 1.3.0
    Contact: team@parallelstack.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import rsearch_client
from rsearch_client.models.create_doc_type_success import CreateDocTypeSuccess  # noqa: E501
from rsearch_client.rest import ApiException


class TestCreateDocTypeSuccess(unittest.TestCase):
    """CreateDocTypeSuccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateDocTypeSuccess(self):
        """Test CreateDocTypeSuccess"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rsearch_client.models.create_doc_type_success.CreateDocTypeSuccess()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
