# coding: utf-8

"""
    ParallelStack RSearch API

    REST API Specification for ParallelStack RSearch API

    OpenAPI spec version: 1.0.0
    Contact: team@parallelstack.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import rsearch_client
from rsearch_client.rest import ApiException
from rsearch_client.models.inline_response_200 import InlineResponse200


class TestInlineResponse200(unittest.TestCase):
    """ InlineResponse200 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200(self):
        """
        Test InlineResponse200
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = rsearch_client.models.inline_response_200.InlineResponse200()
        pass


if __name__ == '__main__':
    unittest.main()
