# coding: utf-8

"""
    ParallelStack RSearch API

    REST API Specification for ParallelStack RSearch API

    OpenAPI spec version: 1.0.0
    Contact: team@parallelstack.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import rsearch_client
from rsearch_client.rest import ApiException
from rsearch_client.models.inline_response_200_1_index import InlineResponse2001Index


class TestInlineResponse2001Index(unittest.TestCase):
    """ InlineResponse2001Index unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001Index(self):
        """
        Test InlineResponse2001Index
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = rsearch_client.models.inline_response_200_1_index.InlineResponse2001Index()
        pass


if __name__ == '__main__':
    unittest.main()
