# coding: utf-8

"""
    ParallelStack RSearch API

    REST API Specification for ParallelStack RSearch API  # noqa: E501

    OpenAPI spec version: 1.3.0
    Contact: team@parallelstack.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import rsearch_client
from rsearch_client.api.rsearch_api import RsearchApi  # noqa: E501
from rsearch_client.rest import ApiException


class TestRsearchApi(unittest.TestCase):
    """RsearchApi unit test stubs"""

    def setUp(self):
        self.api = rsearch_client.api.rsearch_api.RsearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_document(self):
        """Test case for add_document

        """
        pass

    def test_add_document_type(self):
        """Test case for add_document_type

        """
        pass

    def test_add_index(self):
        """Test case for add_index

        """
        pass

    def test_delete_document(self):
        """Test case for delete_document

        """
        pass

    def test_delete_index(self):
        """Test case for delete_index

        """
        pass

    def test_get_advanced_doc_type_suggest_results(self):
        """Test case for get_advanced_doc_type_suggest_results

        """
        pass

    def test_get_advanced_index_suggest_results(self):
        """Test case for get_advanced_index_suggest_results

        """
        pass

    def test_get_advanced_multi_index_search_results(self):
        """Test case for get_advanced_multi_index_search_results

        """
        pass

    def test_get_advanced_multi_index_suggest_results(self):
        """Test case for get_advanced_multi_index_suggest_results

        """
        pass

    def test_get_advanced_search_results(self):
        """Test case for get_advanced_search_results

        """
        pass

    def test_get_all_document_types(self):
        """Test case for get_all_document_types

        """
        pass

    def test_get_all_indexes(self):
        """Test case for get_all_indexes

        """
        pass

    def test_get_basic_search_results(self):
        """Test case for get_basic_search_results

        """
        pass

    def test_get_doc_type_suggest_results(self):
        """Test case for get_doc_type_suggest_results

        """
        pass

    def test_get_document(self):
        """Test case for get_document

        """
        pass

    def test_get_document_type(self):
        """Test case for get_document_type

        """
        pass

    def test_get_index(self):
        """Test case for get_index

        """
        pass

    def test_get_similar_docs_results(self):
        """Test case for get_similar_docs_results

        """
        pass


if __name__ == '__main__':
    unittest.main()
