# coding: utf-8

"""
    ParallelStack RSearch API

    REST API Specification for ParallelStack RSearch API  # noqa: E501

    OpenAPI spec version: 1.2.1
    Contact: team@parallelstack.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import rsearch_client
from rsearch_client.models.suggest_failure import SuggestFailure  # noqa: E501
from rsearch_client.rest import ApiException


class TestSuggestFailure(unittest.TestCase):
    """SuggestFailure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSuggestFailure(self):
        """Test SuggestFailure"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rsearch_client.models.suggest_failure.SuggestFailure()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
