# coding: utf-8

"""
    ParallelStack RSearch API

    REST API Specification for ParallelStack RSearch API  # noqa: E501

    OpenAPI spec version: 1.3.0
    Contact: team@parallelstack.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import rsearch_client
from rsearch_client.models.indexes_search_query_search import IndexesSearchQuerySearch  # noqa: E501
from rsearch_client.rest import ApiException


class TestIndexesSearchQuerySearch(unittest.TestCase):
    """IndexesSearchQuerySearch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndexesSearchQuerySearch(self):
        """Test IndexesSearchQuerySearch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rsearch_client.models.indexes_search_query_search.IndexesSearchQuerySearch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
