# coding: utf-8

"""
    ParallelStack RSearch API

    REST API Specification for ParallelStack RSearch API  # noqa: E501

    OpenAPI spec version: 1.2.1
    Contact: team@parallelstack.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import rsearch_client
from rsearch_client.models.delete_index_failure import DeleteIndexFailure  # noqa: E501
from rsearch_client.rest import ApiException


class TestDeleteIndexFailure(unittest.TestCase):
    """DeleteIndexFailure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteIndexFailure(self):
        """Test DeleteIndexFailure"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rsearch_client.models.delete_index_failure.DeleteIndexFailure()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
