# coding: utf-8

"""
    ParallelStack RSearch API

    REST API Specification for ParallelStack RSearch API  # noqa: E501

    OpenAPI spec version: 1.3.0
    Contact: team@parallelstack.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import rsearch_client
from rsearch_client.models.search_query_search_aggregations import SearchQuerySearchAggregations  # noqa: E501
from rsearch_client.rest import ApiException


class TestSearchQuerySearchAggregations(unittest.TestCase):
    """SearchQuerySearchAggregations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchQuerySearchAggregations(self):
        """Test SearchQuerySearchAggregations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rsearch_client.models.search_query_search_aggregations.SearchQuerySearchAggregations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
